game::logic::tilespawner::TileSpawnerService
List<CreateTileShapeDelegate> game.logic.tilespawner.TileSpawnerService._pieces
Referenced by game.logic.tilespawner.TileSpawnerService.Shuffle, game.logic.tilespawner.TileSpawnerService.Spawn.
Random game.logic.tilespawner.TileSpawnerService.rng
Referenced by game.logic.tilespawner.TileSpawnerService.Shuffle.
delegate ISpawnable game.logic.tilespawner.TileSpawnerService.CreateTileShapeDelegate()
game.logic.tilespawner.TileSpawnerService.TileSpawnerService()
References game.logic.tilespawner.TileSpawnerService.Shuffle.
CreateTileShapeDelegate game.logic.tilespawner.TileSpawnerService.Spawn()
Spawns a new tile shape by shuffling the available pieces and returning the first piece.
A delegate representing the first tile shape after shuffling the pieces. This method first invokes the Shuffle method to randomize the order of the available tile shapes. After shuffling, it retrieves and returns the first tile shape from the collection of pieces. This is useful in scenarios where a random selection of tile shapes is required, such as in game mechanics or puzzle generation. The returned delegate can then be used to create or manipulate the spawned tile shape.
References game.logic.tilespawner.TileSpawnerService._pieces, game.logic.tilespawner.TileSpawnerService.Shuffle.
Referenced by GameRunner.Update.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnIPiece()
Creates and returns a new instance of the IPiece class.
A new instance of IPiece. This method is responsible for instantiating an object of the IPiece type. The IPiece class represents a specific type of spawnable object in the application. By calling this method, users can obtain a fresh instance of IPiece which can then be used in the game or application logic. This method does not take any parameters and is designed to be a simple factory method for creating IPiece objects.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnJPiece()
Creates and returns a new instance of the JPiece object.
A new instance of JPiece that implements the ISpawnable interface. This method is responsible for instantiating the JPiece, which is a specific type of object that can be spawned in the game or application. The returned object can be used to represent a J-shaped piece in a game like Tetris or similar. This method does not take any parameters and provides a straightforward way to obtain a new JPiece instance whenever needed.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnLPiece()
Creates and returns a new instance of the LPiece class.
An instance of LPiece that implements the ISpawnable interface. This method is responsible for instantiating a new LPiece object, which is typically used in games or applications that require the representation of a specific game piece or object. The LPiece class is expected to implement the ISpawnable interface, ensuring that it adheres to the required contract for spawnable objects. This method does not take any parameters and directly returns the newly created LPiece instance.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnOPiece()
Creates and returns a new instance of the OPiece class.
A new instance of OPiece that implements the ISpawnable interface. This method is responsible for instantiating an object of type OPiece, which is expected to implement the ISpawnable interface. The OPiece class represents a specific type of spawnable object within the application, and this method encapsulates the creation logic. By using this method, you ensure that you are always working with a fresh instance of OPiece, which can be useful for managing state and behavior in your application.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnSPiece()
Creates and returns a new instance of the SPiece class.
A new instance of SPiece that implements the ISpawnable interface. This method is responsible for instantiating the SPiece object, which is expected to implement the ISpawnable interface. The SPiece class may contain specific properties and methods that define its behavior in the context of the application. This factory method simplifies the creation of SPiece instances, ensuring that the caller receives a properly initialized object.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnTPiece()
Creates and returns a new instance of the TPiece class.
A new instance of TPiece that implements the ISpawnable interface. This method is responsible for instantiating a TPiece object, which is typically used in games or applications that require a specific type of spawnable entity. The TPiece class is expected to implement the ISpawnable interface, ensuring that it adheres to the necessary contract for spawnable objects. This method does not take any parameters and provides a straightforward way to obtain a new TPiece instance.
static ISpawnable game.logic.tilespawner.TileSpawnerService.SpawnZPiece()
Creates and returns a new instance of the ZPiece.
A new instance of ZPiece that implements the ISpawnable interface. This method is responsible for instantiating a ZPiece object, which is a specific type of spawnable entity in the application. The ZPiece is typically used in contexts where a specific shape or functionality is required, such as in games or simulations. By encapsulating the creation logic in this method, it allows for easier modifications in the future, such as changing the way ZPiece instances are created or initialized.
void game.logic.tilespawner.TileSpawnerService.Shuffle()
Shuffles the elements of the collection randomly.
This method implements the Fisher-Yates shuffle algorithm to randomly reorder the elements in the private collection of pieces. It iterates through the collection, selecting a random index for each element and swapping it with the current element. This ensures that each possible permutation of the collection is equally likely, resulting in a fair shuffle. The method modifies the original collection in place, meaning that the order of elements in _pieces will be changed after this method is called.
References game.logic.tilespawner.TileSpawnerService._pieces, game.logic.tilespawner.TileSpawnerService.rng.
Referenced by game.logic.tilespawner.TileSpawnerService.Spawn, game.logic.tilespawner.TileSpawnerService.TileSpawnerService.