game::logic::EventQueue::EventQueue
Dictionary<EventId, Queue<IEvent> > game.logic.EventQueue.EventQueue._queues
Referenced by game.logic.EventQueue.EventQueue.Dequeue, game.logic.EventQueue.EventQueue.Enqueue, game.logic.EventQueue.EventQueue.EventQueue.
game.logic.EventQueue.EventQueue.EventQueue()
References game.logic.EventQueue.EventQueue._queues.
Referenced by game.logic.playfield.PlayFieldViewModel.Update.
void game.logic.EventQueue.EventQueue.Enqueue(IEvent e)
Adds an event to the appropriate queue based on its identifier.
e The event to be enqueued. This method checks if a queue for the given event's identifier already exists in the internal dictionary. If it does not exist, a new queue is created for that identifier. The event is then added to the corresponding queue. This allows for organizing events by their identifiers, enabling efficient processing of events in a structured manner.
References game.logic.EventQueue.EventQueue._queues, game.logic.EventQueue.IEvent.Id.
Referenced by LoginButton.OnClick, GameRunner.Update.
bool game.logic.EventQueue.EventQueue.HasEvent(EventId id)
Checks if there is at least one event associated with the specified EventId.
id The EventId to check for associated events. True if there is at least one event associated with the specified id ; otherwise, false. This method verifies the presence of an event in the internal data structure, represented by the dictionary _queues . It first checks if the dictionary contains the specified id as a key. If the key exists, it then checks if the corresponding value (a collection of events) has a count greater than zero. This is useful for determining whether any events are queued for processing or handling for a specific identifier.
Referenced by game.logic.EventQueue.EventQueue.Dequeue.
IEvent game.logic.EventQueue.EventQueue.Dequeue(EventId id)
Dequeues an event from the specified event queue identified by the given EventId.
id The identifier of the event queue from which to dequeue the event. An instance of IEvent representing the dequeued event, or null if no event is available for the specified id. This method checks if there is an event available in the queue associated with the provided id . If an event exists, it is removed from the queue and returned. If no event is present for the specified id, the method returns null, indicating that there are no events to dequeue. This is useful for managing event-driven architectures where events are processed in a first-in-first-out (FIFO) manner.
References game.logic.EventQueue.EventQueue._queues, game.logic.EventQueue.EventQueue.HasEvent.